name: Deploy to Azure Container App

on:
  push:
    branches:
      - develop   # run on pushes to develop
  workflow_dispatch:   # allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      imageName: flask-api
      acrName: vikasacr
      resourceGroup: WanchooResourceGroup
      containerAppName: flaskapi-app
      envName: vikas-env

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.acrName }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ env.acrName }}.azurecr.io/${{ env.imageName }}:${{ github.run_id }} .
        docker push ${{ env.acrName }}.azurecr.io/${{ env.imageName }}:${{ github.run_id }}

    - name: Deploy Container App
      run: |
        az containerapp create \
          --name ${{ env.containerAppName }} \
          --resource-group ${{ env.resourceGroup }} \
          --environment ${{ env.envName }} \
          --image ${{ env.acrName }}.azurecr.io/${{ env.imageName }}:${{ github.run_id }} \
          --target-port 5000 \
          --ingress external \
          --registry-server ${{ env.acrName }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --query properties.configuration.ingress.fqdn
